# -*- coding: utf-8 -*-
"""Classifying Malignancy of Breast Cancer using its size data and SVM ML Algorithm

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KRf5k-sodQUA-bJr_fvw0MRCkXkR5_qP
"""

#import statements
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
import pandas as pd
from sklearn import metrics

#import dataset
data = datasets.load_breast_cancer()

print(data.feature_names)
print(data.target_names)

#vizualization
df = pd.DataFrame(data=data.data, columns=data.feature_names)
df

#splitting data
x = data.data
y = data.target
print(y)
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

classes = list(data.target_names)
classes

#build model
model = SVC(kernel='linear')
model.fit(x_train, y_train)

prediction = model.predict(x_test)
metrics.accuracy_score(y_test, prediction)